Revise CI pipeline for better error handling and tagging
Updated CI pipeline configuration to include enhanced error handling for deployment manifest updates and improved image tagging.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -141,9 +141,19 @@ jobs:
       - name: Update Kubernetes manifest
         run: |
           cd weather-config
-          FILE_PATH=$(find . -name "deployment.yml")
+           # Search for deployment.yml or deployment.yaml case-insensitively
+          FILE_PATH=$(find . -iname "deployment.y*ml" | head -n 1)
+          
+          if [ -z "$FILE_PATH" ]; then
+            echo "ERROR: Could not find deployment.yml in the main branch."
+            ls -R
+            exit 1
+          fi
+          
+          echo "Updating: $FILE_PATH"
+          
+          # Replace the image line
           sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/weather-news-dashboard:${{ needs.build-and-push.outputs.image_tag }}|g" "$FILE_PATH"
-
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git add .
